import type { Category, Product, VideoItem } from './types'

export const SEED_CATEGORIES: Category[] = [
  {
    id: 'sharqi',
    name: { ar: 'شرقي', he: 'מזרחי' },
    desc: { ar: 'عود وعنبر ومسك', he: 'אוד, ענבר ומושק' },
    color: '#d4a24c',
  },
  {
    id: 'khashabi',
    name: { ar: 'خشبي', he: 'עצי' },
    desc: { ar: 'أرز وجلد وفيتيفر', he: 'ארז, עור ווטיבר' },
    color: '#a98963',
  },
  {
    id: 'munash',
    name: { ar: 'منعش', he: 'מרענן' },
    desc: { ar: 'حمضيات ونسيم بحر', he: 'הדרים ובריזה' },
    color: '#5fb7cf',
  },
  {
    id: 'tawabil',
    name: { ar: 'توابل', he: 'תבלינים' },
    desc: { ar: 'قرفة وفلفل وقرنفل', he: 'קינמון, פלפל וציפורן' },
    color: '#d96c3f',
  },
]

export const SEED_BRANDS = ['دار أشور', 'عود الذهب', 'مسك الشرق', 'عنبر هاوس', 'رمال']

export const SEED_PRODUCTS: Product[] = [
  {
    id: 'p1',
    name: { ar: 'عود الملوك', he: 'אוד אל-מולוכ' },
    latin: 'OUD AL MOLOOK',
    brand: 'عود الذهب',
    categoryId: 'sharqi',
    priceNum: 480,
    oldPriceNum: 560,
    isBestSeller: true,
    description: {
      ar: 'عود كمبودي فاخر يُعجن بالزعفران والورد الطائفي، ويستقر على قاعدة من العنبر والمسك. حضورٌ ملكي لا يُنسى.',
      he: 'אוד קמבודי יוקרתי עם זעפרן וורד טאיף, על בסיס ענבר ומושק. נוכחות מלכותית בלתי נשכחת.',
    },
    notes: {
      ar: { top: ['زعفران', 'هيل'], heart: ['عود كمبودي', 'ورد طائفي'], base: ['عنبر', 'مسك', 'صندل'] },
      he: { top: ['זעפרן', 'הל'], heart: ['אוד קמבודי', 'ורד טאיף'], base: ['ענבר', 'מושק', 'סנדל'] },
    },
    longevity: { ar: 'ثبات ١٥+ ساعة', he: 'עמידות 15+ שעות' },
    intensity: 5,
    variant: 0,
    colors: { accent: '#d4a24c', liquid: '#7a4a12' },
  },
  {
    id: 'p2',
    name: { ar: 'ليل الصحراء', he: 'ליל המדבר' },
    latin: 'DESERT NIGHT',
    brand: 'رمال',
    categoryId: 'khashabi',
    priceNum: 390,
    description: {
      ar: 'دفء الجلد وعمق الباتشولي تحت سماء صحراوية صافية، مع لمسة فانيليا تليّق بسهرات الشتاء الطويلة.',
      he: 'חמימות עור ועומק פצ׳ולי תחת שמי מדבר, עם נגיעת וניל ללילות חורף ארוכים.',
    },
    notes: {
      ar: { top: ['برغموت', 'فلفل وردي'], heart: ['جلد فاخر', 'باتشولي'], base: ['عود', 'فانيليا'] },
      he: { top: ['ברגמוט', 'פלפל ורוד'], heart: ['עור יוקרתי', 'פצ׳ולי'], base: ['אוד', 'וניל'] },
    },
    longevity: { ar: 'ثبات ١٢+ ساعة', he: 'עמידות 12+ שעות' },
    intensity: 4,
    variant: 1,
    colors: { accent: '#c78d4e', liquid: '#5c3a1e' },
  },
  {
    id: 'p3',
    name: { ar: 'نسمة المحيط', he: 'משב האוקיינוס' },
    latin: 'OCEAN BREEZE',
    brand: 'عنبر هاوس',
    categoryId: 'munash',
    priceNum: 320,
    isNew: true,
    description: {
      ar: 'نسيم مالح يحمل نفحات الليمون والنعناع فوق قلب من الملح البحري، ليمنحك انتعاش الصباح في أي وقت.',
      he: 'בריזה מלוחה עם לימון ונענע על לב של מלח ים — רעננות בוקר בכל שעה.',
    },
    notes: {
      ar: { top: ['ليمون', 'نعناع'], heart: ['ملح بحري', 'لافندر'], base: ['مسك أبيض', 'خشب الأرز'] },
      he: { top: ['לימון', 'נענע'], heart: ['מלח ים', 'לבנדר'], base: ['מושק לבן', 'ארז'] },
    },
    longevity: { ar: 'ثبات ٨ ساعات', he: 'עמידות 8 שעות' },
    intensity: 3,
    variant: 2,
    colors: { accent: '#5fb7cf', liquid: '#1f6f86' },
  },
  {
    id: 'p4',
    name: { ar: 'طريق التوابل', he: 'דרך התבלינים' },
    latin: 'SPICE ROUTE',
    brand: 'مسك الشرق',
    categoryId: 'tawabil',
    priceNum: 420,
    isBestSeller: true,
    description: {
      ar: 'رحلة قوافل التوابل القديمة: فلفل أسود وجوزة الطيب يلتقيان بالقرفة والقرنفل على سرير من خشب الأرز.',
      he: 'מסע שיירות התבלינים: פלפל שחור ואגוז מוסקט פוגשים קינמון וציפורן על עץ ארז.',
    },
    notes: {
      ar: { top: ['فلفل أسود', 'جوزة الطيب'], heart: ['قرفة', 'قرنفل'], base: ['خشب الأرز', 'تبغ عسلي'] },
      he: { top: ['פלפל שחור', 'אגוז מוסקט'], heart: ['קינמון', 'ציפורן'], base: ['עץ ארז', 'טבק דבש'] },
    },
    longevity: { ar: 'ثبات ١٠+ ساعات', he: 'עמידות 10+ שעות' },
    intensity: 4,
    variant: 0,
    colors: { accent: '#d96c3f', liquid: '#8a3212' },
  },
  {
    id: 'p5',
    name: { ar: 'عنبر الليل', he: 'ענבר הלילה' },
    latin: 'AMBER NOIR',
    brand: 'عود الذهب',
    categoryId: 'sharqi',
    priceNum: 540,
    oldPriceNum: 640,
    isBestSeller: true,
    description: {
      ar: 'عنبر سائل يتوهج في الظلام، يتصاعد من قلب اللبان واللابدانوم إلى فانيليا دافئة تُروى الحكايات على ضوء الشموع.',
      he: 'ענבר נוזלי הזוהר בחושך, מלבונה ולבדנום לוניל חמים לאור נרות.',
    },
    notes: {
      ar: { top: ['برتقال دموي'], heart: ['لبان', 'لابدانوم'], base: ['عنبر', 'فانيليا', 'باتشولي'] },
      he: { top: ['תפוז דם'], heart: ['לבונה', 'לבדנום'], base: ['ענבר', 'וניל', 'פצ׳ולי'] },
    },
    longevity: { ar: 'ثبات ١٦+ ساعة', he: 'עמידות 16+ שעות' },
    intensity: 5,
    variant: 1,
    colors: { accent: '#e0a83f', liquid: '#915c10' },
  },
  {
    id: 'p6',
    name: { ar: 'أرز الأطلس', he: 'ארז האטלס' },
    latin: 'CEDAR ATLAS',
    brand: 'رمال',
    categoryId: 'khashabi',
    priceNum: 350,
    description: {
      ar: 'غابات الأرز الأطلسي بعد المطر: نفحة جريب فروت منعشة تفتح الطريق لقلب خشبي أخضر هادئ ومتوازن.',
      he: 'יערות הארז אחרי הגשם: אשכולית רעננה פותחת לב עצי ירוק ורגוע.',
    },
    notes: {
      ar: { top: ['جريب فروت'], heart: ['أرز أطلسي', 'إكليل الجبل'], base: ['فيتيفر', 'مسك'] },
      he: { top: ['אשכולית'], heart: ['ארז אטלסי', 'רוזמרין'], base: ['וטיבר', 'מושק'] },
    },
    longevity: { ar: 'ثبات ٩ ساعات', he: 'עמידות 9 שעות' },
    intensity: 3,
    variant: 2,
    colors: { accent: '#9caf88', liquid: '#4a5d3a' },
  },
  {
    id: 'p7',
    name: { ar: 'فجر الحمضيات', he: 'שחר ההדרים' },
    latin: 'CITRUS DAWN',
    brand: 'عنبر هاوس',
    categoryId: 'munash',
    priceNum: 290,
    isNew: true,
    description: {
      ar: 'يوزو وليمون صقلي يفجّران الطاقة مع أول ضوء، يتبعهما شاي أخضر ونيرولي في توازن مثالي للنهار.',
      he: 'יוזו ולימון סיציליאני מתפרצים עם אור ראשון, ואחריהם תה ירוק ונרולי.',
    },
    notes: {
      ar: { top: ['يوزو', 'ليمون صقلي'], heart: ['نيرولي', 'شاي أخضر'], base: ['مسك ناعم'] },
      he: { top: ['יוזו', 'לימון סיציליאני'], heart: ['נרולי', 'תה ירוק'], base: ['מושק עדין'] },
    },
    longevity: { ar: 'ثبات ٧ ساعات', he: 'עמידות 7 שעות' },
    intensity: 3,
    variant: 0,
    colors: { accent: '#e8c94f', liquid: '#b58a12' },
  },
  {
    id: 'p8',
    name: { ar: 'مسك الأسود', he: 'המושק השחור' },
    latin: 'BLACK MUSK',
    brand: 'دار أشور',
    categoryId: 'sharqi',
    priceNum: 460,
    isBestSeller: true,
    description: {
      ar: 'مسك أسود غامض يلتف حول الورد الدمشقي والعود، بعمقٍ شرقي أصيل يترك أثراً في كل غرفة تدخلها.',
      he: 'מושק שחור מסתורי סביב ורד דמשקאי ואוד — עומק מזרחי אותנטי.',
    },
    notes: {
      ar: { top: ['هيل'], heart: ['مسك أسود', 'ورد دمشقي'], base: ['عود', 'عنبر'] },
      he: { top: ['הל'], heart: ['מושק שחור', 'ורד דמשקאי'], base: ['אוד', 'ענבר'] },
    },
    longevity: { ar: 'ثبات ١٤+ ساعة', he: 'עמידות 14+ שעות' },
    intensity: 4,
    variant: 2,
    colors: { accent: '#9b7bb8', liquid: '#4a2d66' },
  },
  {
    id: 'p9',
    name: { ar: 'جلد ودخان', he: 'עור ועשן' },
    latin: 'LEATHER & SMOKE',
    brand: 'دار أشور',
    categoryId: 'khashabi',
    priceNum: 510,
    oldPriceNum: 590,
    description: {
      ar: 'جلد مدبوغ يدوياً ودخان خشب البتولا في تركيبة جسورة لمن لا يخشى التميّز — عطر الفصول الباردة بلا منازع.',
      he: 'עור מעובד ועשן ליבנה בתרכובת נועזת — הבושם של העונה הקרה.',
    },
    notes: {
      ar: { top: ['فلفل وردي'], heart: ['جلد مدبوغ', 'خشب الغاياك'], base: ['دخان البتولا', 'فيتيفر'] },
      he: { top: ['פלפל ורוד'], heart: ['עור מעובד', 'גוואיאק'], base: ['עשן ליבנה', 'וטיבר'] },
    },
    longevity: { ar: 'ثبات ١٥+ ساعة', he: 'עמידות 15+ שעות' },
    intensity: 5,
    variant: 1,
    colors: { accent: '#a98963', liquid: '#4e3421' },
  },
  {
    id: 'p10',
    name: { ar: 'قرفة العنبر', he: 'קינמון וענבר' },
    latin: 'CINNAMON AMBER',
    brand: 'مسك الشرق',
    categoryId: 'tawabil',
    priceNum: 370,
    isNew: true,
    description: {
      ar: 'قرفة دافئة تُقدَّم مع البرتقال والتمر، وتحلّ عنبرياً على قاعدة التونكا — عطر مسائي يجمع الفخامة والود.',
      he: 'קינמון חם עם תפוז ותמרים על בסיס ענבר וטונקה — ערב יוקרתי וחם.',
    },
    notes: {
      ar: { top: ['قرفة', 'برتقال'], heart: ['تمر', 'لبان'], base: ['عنبر', 'تونكا'] },
      he: { top: ['קינמון', 'תפוז'], heart: ['תמרים', 'לבונה'], base: ['ענבר', 'טונקה'] },
    },
    longevity: { ar: 'ثبات ١١+ ساعة', he: 'עמידות 11+ שעות' },
    intensity: 4,
    variant: 0,
    colors: { accent: '#c25e4a', liquid: '#7e2f1e' },
  },
]

export const SEED_VIDEOS: VideoItem[] = [
  {
    id: 'v1',
    title: { ar: 'من البذرة إلى العطر', he: 'מהזרע לבושם' },
    src: '/videos/reel-1.mp4',
    poster: '/videos/reel-1.jpg',
  },
  {
    id: 'v2',
    title: { ar: 'حرفة الأرض', he: 'מלאכת האדמה' },
    src: '/videos/reel-2.mp4',
    poster: '/videos/reel-2.jpg',
  },
  {
    id: 'v3',
    title: { ar: 'روح الحمضيات', he: 'רוח ההדרים' },
    src: '/videos/reel-3.mp4',
    poster: '/videos/reel-3.jpg',
  },
]
